using Test
using BloomEvents

include("test_climatology.jl")
include("test_baseline_years.jl")
include("test_anomalies_persistence.jl")
include("test_thresholds_categories.jl")
include("test_pipeline.jl")
include("test_events.jl")
include("test_analyze_bloom.jl")
include("test_metrics.jl")
include("test_annual.jl")
include("test_export.jl")
include("test_spatial.jl")
include("test_spatial_stack.jl")
include("test_spatial_trends.jl")
include("test_spatial_categories.jl")
include("test_spatial_trends_missing.jl")
include("test_spatial_categories_events.jl")
include("test_spatial_peak_events.jl")
include("test_qa.jl")
include("test_qa_integration.jl")
