name = "BloomEvents"
uuid = "30d135c3-80e7-4161-98dc-7057595b7748"
version = "0.1.0"
authors = ["Saif Mehjabin "]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.9"
Dates = "1"
Statistics = "1"
CairoMakie = "0.15"
NCDatasets = "0.14"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[weakdeps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"

[extensions]
BloomEventsCairoMakieExt = "CairoMakie"
BloomEventsNCDatasetsExt = "NCDatasets"
